// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cojrctplwzfrdmqkexhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvanJjdHBsd3pmcmRtcWtleGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjA3NjksImV4cCI6MjA2MzkzNjc2OX0.4Wp0q8wUYr6CQ6J0f-8LXhxL1vuCbgfLo1_PoiEfkVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);